const constants = {
    LOGGED_IN: 'LOGGED_IN',
    LOGGING_IN: 'LOGGING_IN',
    LOGGING_IN_FAILED: 'LOGGING_IN_FAILED',

    LOGOUT: 'LOGOUT',

    LOADING_PROFILE: 'LOADING_PROFILE',
    PROFILE_LOADED: 'PROFILE_LOADED',
    PROFILE_NOT_LOADED: 'PROFILE_NOT_LOADED',

    LOADING_NEWS: 'LOADING_NEWS',
    NEWS_LOADED: 'NEWS_LOADED',
    NEWS_NOT_LOADED: 'NEWS_NOT_LOADED',

    SET_ERROR: 'SET_ERROR',
    RELEASE_ERROR: 'RELEASE_ERROR',
};

export default constants;
